# Use the OpenJDK 17 Alpine base image
FROM openjdk:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Gradle wrapper files (gradle-wrapper.jar and gradle-wrapper.properties)
COPY gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties ./gradle/wrapper/

# Copy the Gradle wrapper shell script (gradlew) and give it executable permissions
COPY gradlew ./
RUN chmod +x gradlew

# Copy the Gradle build files (build.gradle and settings.gradle)
COPY build.gradle settings.gradle ./

# Copy the entire application source code
COPY src ./src

# Run the Gradle clean build command while excluding specified tasks
RUN ./gradlew clean build

# Expose the port your Spring Boot application will run on (adjust as needed)
EXPOSE 8080

# Command to run the Spring Boot application
CMD ["java", "-jar", "build/libs/spring-angular-integration-0.0.1-SNAPSHOT.jar"]
